###
#   Logging Settings
###
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ROOT: INFO

###
#   Database Settings
###
#profiles: securityOn, userData, testData
spring:
  profiles:
    active: securityOn
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: false
        use_sql_comments: false
        format_sql: false
    database: postgresql
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test
    driverClassName: org.postgresql.Driver